name: aws_interop
description: Dart wrapper for Amazon AWS
version: 1.1.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://www.github.com/johnpryan/aws-dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <1.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: '>=0.10.0 <0.11.0'
